# Generated by Django 4.1.7 on 2023-03-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('a_Id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('m_Id', models.IntegerField(max_length=10)),
                ('a_Account', models.CharField(max_length=20, unique=True)),
                ('a_Password', models.CharField(max_length=20)),
                ('a_Level', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_Id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('m_Name', models.CharField(max_length=10, unique=True)),
                ('m_Gender', models.CharField(default='m', max_length=2)),
                ('m_Old', models.IntegerField(max_length=10)),
                ('m_Email', models.EmailField(blank=True, default='', max_length=100)),
                ('m_Phone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('s_Id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('s_Lang', models.CharField(max_length=10)),
                ('s_Name', models.CharField(max_length=50, unique=True)),
                ('s_Summary', models.CharField(max_length=400)),
                ('s_Introduction', models.TextField(max_length=400)),
                ('s_OpenTime', models.CharField(max_length=2000)),
                ('s_District', models.CharField(max_length=50)),
                ('s_Address', models.CharField(max_length=100)),
                ('s_Tel', models.CharField(max_length=20)),
                ('s_Fax', models.CharField(max_length=50)),
                ('s_Latitude', models.FloatField(max_length=10)),
                ('s_Longtitude', models.FloatField(max_length=10)),
                ('s_Services', models.CharField(max_length=100)),
                ('s_Category', models.CharField(max_length=100)),
                ('s_UpdateTime', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
