# Generated by Django 4.1.7 on 2023-05-18 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="travel_list_detail", name="tl_StartTime",),
        migrations.AlterField(
            model_name="travel_list_detail",
            name="tl_Notes",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="travel_list_detail",
            name="tl_TransportMode",
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="travel_list_detail",
            name="tl_TransportTime",
            field=models.IntegerField(null=True),
        ),
        migrations.CreateModel(
            name="Travel_List_StartTime",
            fields=[
                ("tls_Id", models.AutoField(primary_key=True, serialize=False)),
                ("tls_Day", models.IntegerField(default=1)),
                ("tls_StartTime", models.IntegerField(default=28800)),
                (
                    "t_Id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.travel_list",
                    ),
                ),
            ],
        ),
    ]
