# Generated by Django 3.2.9 on 2023-03-16 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='f_Introduction',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='food',
            name='f_Summary',
            field=models.CharField(max_length=1000),
        ),
    ]
