# Generated by Django 4.1.6 on 2023-03-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='f_Summary',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='h_Summary',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
