# Generated by Django 4.1.7 on 2023-03-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_Id', models.CharField(max_length=10)),
                ('a_Account', models.CharField(max_length=20)),
                ('a_Password', models.CharField(max_length=20)),
                ('a_Level', models.IntegerField()),
            ],
        ),
    ]
