# Generated by Django 3.2.9 on 2023-03-09 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='s_Tel',
            field=models.CharField(max_length=50),
        ),
    ]
