# Generated by Django 3.2.9 on 2023-03-09 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_spot_s_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spot',
            name='s_Introduction',
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='spot',
            name='s_Summary',
            field=models.CharField(max_length=2000),
        ),
    ]
