# Generated by Django 4.1.7 on 2023-03-06 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='a_Id',
        ),
    ]
