# Generated by Django 3.2.9 on 2023-03-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20230309_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_picture',
            name='mp_URL',
            field=models.ImageField(default=None, upload_to='images/member/'),
        ),
        migrations.AlterField(
            model_name='s_picture',
            name='sp_URL',
            field=models.ImageField(default=None, upload_to='images/spot/'),
        ),
    ]
