# Generated by Django 3.2.9 on 2023-03-13 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20230310_2347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='s_picture',
            name='s_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.spot'),
        ),
    ]
